openapi: 3.1.0
info:
  title: Snail API
  description: A simple snail API for interacting with snail images and information.
  version: 1.0.0
  contact:
    email: rwim@naver.com
    url: 'https://www.linkedin.com/in/sungjin-shin-88b5b8130'
  x-logo:
    url: 'https://redocly.github.io/redoc/museum-logo.png'
    altText: Snail logo
  license:
    name: MIT
    url: 'https://opensource.org/license/mit/ '
servers:
  - url: 'https://api.fake-museum-example.com/v1'
paths:
  '/snail/{SnailId}':
    get:
      summary: Get a snail image
      description: Return a specific snail image using specific ID
      operationId: getSnailById
      tags:
        - Images
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSnailImage'
              examples:
                default:
                  $ref: '#/components/examples/GetSnailRawImageExample'
                mobile:
                  $ref: '#/components/examples/GetSnailMobileImageExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  /snail:
    get:
      summary: List snail images
      description: Return a list of snail images.
      operationId: listSnailImages
      tags:
        - Images
      parameters:
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSnailImagesResponse'
              examples:
                default:
                  $ref: '#/components/examples/ListSnailImagesRawResponseExample'
                mobile:
                  $ref: '#/components/examples/ListSnailImagesMobileResponseExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  /random:
    get:
      summary: List random snail images
      description: Return a list of random snail images.
      operationId: listRandomSnailImages
      tags:
        - Images
      parameters:
        - $ref: '#/components/parameters/Count'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSnailImagesResponse'
              examples:
                default:
                  $ref: '#/components/examples/ListRandomSnailImagesRawResponseExample'
                mobile:
                  $ref: '#/components/examples/ListRandomSnailImagesMobileResponseExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  '/info/{InfoId}':
    get:
      summary: Get a snail info using ID
      description: Return a specific snail info using specific ID
      operationId: getInfoById
      tags:
        - Info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSnailInfo'
              examples:
                default:
                  $ref: '#/components/examples/GetSnailInfoExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  '/info/{Category}':
    get:
      summary: Get a snail info using category
      description: Return a specific snail info using specific category
      operationId: getInfoByCategory
      tags:
        - Info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSnailInfo'
              examples:
                default:
                  $ref: '#/components/examples/GetSnailInfoExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  /info:
    get:
      summary: Get all snail information
      description: Return all snail information
      operationId: getAllInfo
      tags:
        - Info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllSnailInfoResponse'
              examples:
                default:
                  $ref: '#/components/examples/AllSnailInfoResponseExample'
        '400':
          description: Bad request
        '404':
          description: Not found
    post:
      operationId: RegisterInfo
      summary: Register a snail information
      tags:
        - Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterSnailInfo'
            examples:
              default_example:
                $ref: '#/components/examples/RegisterSnailInfoExample'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSnailInfoResponse'
              examples:
                default_example:
                  $ref: '#/components/examples/RegisterSnailInfoResponseExample'
        '400':
          description: Bad request
        '404':
          description: Not found
  /info/intro:
    get:
      summary: Introduction
      description: Return a content about snail API.
      operationId: getIntroducedInfo
      tags:
        - Info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIntroducedInfo'
              example:
                $ref: '#/components/examples/GetIntroducedInfoExample'
components:
  schemas:
    SnailId:
      description: Snail ID
      type: integer
      example: 1
    RegisterDate:
      description: Register Date
      type: string
      example: '2024-09-30'
    InfoId:
      decription: Information ID
      type: integer
      example: 1
    ImageUrl:
      description: Image URL
      type: string
      example: 'https://example.com/raw/240930_0001.png'
    InfoCategory:
      description: Category of informations
      type: string
      example: 'Property'
    InfoContent:
      description: Category of informations
      type: string
      example: 'A snail eats ...'
    GetSnailImage:
      description: Single image information
      type: object
      properties:
        id:
          $ref: '#/components/schemas/SnailId'
        date:
          $ref: '#/components/schemas/RegisterDate'
        url:
          $ref: '#/components/schemas/ImageUrl'
    GetSnailInfo:
      description: Single information
      type: object
      properties:
        id:
          $ref: '#/components/schemas/InfoId'
        date:
          $ref: '#/components/schemas/RegisterDate'
        category:
          $ref: '#/components/schemas/InfoCategory'
        content:
          $ref: '#/components/schemas/InfoContent'
    ListSnailImagesResponse:
      description: A list of snail images
      type: array
      items:
        $ref: '#/components/schemas/GetSnailImage'
    AllSnailInfoResponse:
      description: All snail information
      type: array
      items:
        $ref: '#/components/schemas/GetSnailInfo'
    GetIntroducedInfo:
      description: The snail API introduction
      type: object
      properties:
        title:
          description: The title of introduction
          type: string
          example: Introduce the snail API
        content:
          description: The content of introduction
          type: string
          example: Welcome the snail API
        environment:
          $ref: '#/components/schemas/GetEnvInfo'
    GetEnvInfo:
      description: Introduction of the environment about the snail API
      type: object
      properties:
        platform: 
          description: Deployment platform
          type: string
          example: Serverless architecture
        compute:
          description: Compute Engine
          type: string
          example: AWS Lambda
        api:
          description: API Engine
          type: string
          example: API Gateway
        database: 
          description: Database for saving metadata
          type: string
          example: DynamoDB
        storage: 
          description: Image and static pages for saving data
          type: string
          example: Amazon S3
    RegisterSnailInfo:
      description: Request payload for registering new snail information.
      type: object
      properties:
        category:
          $ref: '#/components/schemas/InfoCategory'
        content:
          $ref: '#/components/schemas/InfoContent'
      required:
        - category
        - content
    RegisterSnailInfoResponse:
      description: Information about the registered information.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/InfoId"
        date:
          $ref: "#/components/schemas/RegisterDate"
        category:
          $ref: '#/components/schemas/InfoCategory'
        content:
          $ref: '#/components/schemas/InfoContent'
      required:
        - id
        - date
        - category
        - content
  examples:
    GetSnailRawImageExample:
      summary: Raw Image
      value:
        id: 1
        date: '2024-09-30'
        url: 'https://example.com/images/raw/473806aff17779875691.png'
    GetSnailMobileImageExample:
      summary: Mobile Image
      value:
        id: 1
        date: '2024-09-30'
        url: 'https://example.com/images/mobile/473806aff17779875691.png'
    GetSnailInfoExample:
      summary: A Snail Inforatmion
      value:
        id: 1
        date: '2024-09-30'
        category: 'Property'
        content: 'A snail eats...'        
    RegisterSnailInfoExample:
      summary: Register a snail information
      value:
        category: 'Property'
        content: 'A snail eats ...'
    RegisterSnailInfoResponseExample:
      summary: Response about a snail information registration
      value:
        id: 1
        date: '2024-09-30'
        category: 'Property'
        content: 'A snail eats ...'
    ListSnailImagesRawResponseExample:
      summary: Raw Images
      value:
        - id: 1
          date: '2024-09-28'
          url: 'https://example.com/images/raw/473806aff17779875691.png'
        - id: 2
          date: '2024-09-29'
          url: 'https://example.com/images/raw/473806aff17779875692.png'
        - id: 3
          date: '2024-09-30'
          url: 'https://example.com/images/raw/473806aff17779875693.png'
    ListSnailImagesMobileResponseExample:
      summary: Mobile Images
      value:
        - id: 1
          date: '2024-09-22'
          url: 'https://example.com/images/mobile/473806aff17779875691.png'
        - id: 2
          date: '2024-09-23'
          url: 'https://example.com/images/mobile/473806aff17779875692.png'
        - id: 3
          date: '2024-09-24'
          url: 'https://example.com/images/mobile/473806aff17779875693.png'
    ListRandomSnailImagesRawResponseExample:
      summary: Raw Images
      value:
        - id: 3
          date: '2024-09-29'
          url: 'https://example.com/images/raw/473806aff17779875691.png'
        - id: 1
          date: '2024-09-28'
          url: 'https://example.com/images/raw/473806aff17779875692.png'
        - id: 2
          date: '2024-09-30'
          url: 'https://example.com/images/raw/473806aff17779875693.png'
    ListRandomSnailImagesMobileResponseExample:
      summary: Mobile Images
      value:
        - id: 4
          date: '2024-09-30'
          url: 'https://example.com/images/mobile/473806aff17779875691.png'
        - id: 1
          date: '2024-09-22'
          url: 'https://example.com/images/mobile/473806aff17779875692.png'
        - id: 2
          date: '2024-09-25'
          url: 'https://example.com/images/mobile/473806aff17779875693.png'
    AllSnailInfoResponseExample:
      summary: All Snail Inforatmion
      value:
        - id: 1
          date: '2024-09-30'
          category: 'Property'
          content: 'A snail eats...'
        - id: 2
          date: '2024-10-22'
          category: 'Lissachatina fulica'
          content: 'Lissachatina fulica is a species of large land snail...'
    GetIntroducedInfoExample:
      value:
        title: Introduce the snail API
        content: Welcome the snail API
        environment:
          platform: Serverless architecture
          compute: AWS Lambda
          api: API Gateway
          database: DynamoDB
          storage: Amazon S3
  parameters:
    SnailId:
      name: id
      in: query
      description: The snail ID.
      schema:
        type: integer
        example: 1
    StartDate:
      name: startDate
      in: query
      description: The starting date to retrieve future operating hours from. Defaults to today's date.
      schema:
        type: string
        format: date
        example: 2023-02-23
    EndDate:
      name: endDate
      in: query
      description: The end of a date range to retrieve special events for. Defaults to 7 days after `startDate`.
      schema:
        type: string
        format: date
        example: 2023-04-18
    Page:
      name: page
      in: query
      description: The page number to retrieve.
      schema:
        type: integer
        default: 1
        example: 2
    Limit:
      name: limit
      in: query
      description: The number of data per page.
      schema:
        type: integer
        default: 10
        maximum: 30
        example: 15
    Count:
      name: count
      in: query
      description: The number of data.
      schema:
        type: integer
        default: 10
        maximum: 30
        example: 15

tags:
  - name: Images
    x-displayName: Images
    description: Images for some snails
  - name: Info
    x-displayName: Info
    description: Information about snails
